<?xml version="1.0" encoding="utf-8"?><Database Name="prayers" Class="prayDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\prayers.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="prayersConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.prayer1" Member="prayers">
    <Type Name="prayer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="masjid_area" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="masjid_name" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="fajr_time" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="zuhr_time" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="asar_time" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="magrib_time" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="esha_time" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>