#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mini_project.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="prayers")]
	public partial class prayDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertprayer(prayer instance);
    partial void Updateprayer(prayer instance);
    partial void Deleteprayer(prayer instance);
    #endregion
		
		public prayDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["prayersConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public prayDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public prayDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public prayDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public prayDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<prayer> prayers
		{
			get
			{
				return this.GetTable<prayer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.prayer1")]
	public partial class prayer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _masjid_area;
		
		private string _masjid_name;
		
		private string _fajr_time;
		
		private string _zuhr_time;
		
		private string _asar_time;
		
		private string _magrib_time;
		
		private string _esha_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onmasjid_areaChanging(string value);
    partial void Onmasjid_areaChanged();
    partial void Onmasjid_nameChanging(string value);
    partial void Onmasjid_nameChanged();
    partial void Onfajr_timeChanging(string value);
    partial void Onfajr_timeChanged();
    partial void Onzuhr_timeChanging(string value);
    partial void Onzuhr_timeChanged();
    partial void Onasar_timeChanging(string value);
    partial void Onasar_timeChanged();
    partial void Onmagrib_timeChanging(string value);
    partial void Onmagrib_timeChanged();
    partial void Onesha_timeChanging(string value);
    partial void Onesha_timeChanged();
    #endregion
		
		public prayer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masjid_area", DbType="NChar(100)")]
		public string masjid_area
		{
			get
			{
				return this._masjid_area;
			}
			set
			{
				if ((this._masjid_area != value))
				{
					this.Onmasjid_areaChanging(value);
					this.SendPropertyChanging();
					this._masjid_area = value;
					this.SendPropertyChanged("masjid_area");
					this.Onmasjid_areaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masjid_name", DbType="NChar(100)")]
		public string masjid_name
		{
			get
			{
				return this._masjid_name;
			}
			set
			{
				if ((this._masjid_name != value))
				{
					this.Onmasjid_nameChanging(value);
					this.SendPropertyChanging();
					this._masjid_name = value;
					this.SendPropertyChanged("masjid_name");
					this.Onmasjid_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fajr_time", DbType="NChar(50)")]
		public string fajr_time
		{
			get
			{
				return this._fajr_time;
			}
			set
			{
				if ((this._fajr_time != value))
				{
					this.Onfajr_timeChanging(value);
					this.SendPropertyChanging();
					this._fajr_time = value;
					this.SendPropertyChanged("fajr_time");
					this.Onfajr_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zuhr_time", DbType="NChar(50)")]
		public string zuhr_time
		{
			get
			{
				return this._zuhr_time;
			}
			set
			{
				if ((this._zuhr_time != value))
				{
					this.Onzuhr_timeChanging(value);
					this.SendPropertyChanging();
					this._zuhr_time = value;
					this.SendPropertyChanged("zuhr_time");
					this.Onzuhr_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_asar_time", DbType="NChar(50)")]
		public string asar_time
		{
			get
			{
				return this._asar_time;
			}
			set
			{
				if ((this._asar_time != value))
				{
					this.Onasar_timeChanging(value);
					this.SendPropertyChanging();
					this._asar_time = value;
					this.SendPropertyChanged("asar_time");
					this.Onasar_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magrib_time", DbType="NChar(50)")]
		public string magrib_time
		{
			get
			{
				return this._magrib_time;
			}
			set
			{
				if ((this._magrib_time != value))
				{
					this.Onmagrib_timeChanging(value);
					this.SendPropertyChanging();
					this._magrib_time = value;
					this.SendPropertyChanged("magrib_time");
					this.Onmagrib_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esha_time", DbType="NChar(50)")]
		public string esha_time
		{
			get
			{
				return this._esha_time;
			}
			set
			{
				if ((this._esha_time != value))
				{
					this.Onesha_timeChanging(value);
					this.SendPropertyChanging();
					this._esha_time = value;
					this.SendPropertyChanged("esha_time");
					this.Onesha_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
